steps:
- checkout: self
  clean: true
  fetchDepth: 1
  
- checkout: msgraph-sdk-powershell
  clean: true
  fetchDepth: 1
  submodules: true
  persistCredentials: true

- checkout:microsoft-graph-docs
  clean: true
  fetchDepth: 1
  submodules: true
  persistCredentials: true