# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 2 LTS'
      inputs:
        debugMode: false
        version: 2.x

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3 LTS'
      inputs:
        debugMode: false
        version: 3.x

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 6 Current'
      inputs:
        debugMode: false
        version: 6.x

    - task: NodeTool@0
      displayName: 'Install NodeJs'
      inputs:
        versionSpec: '14.18.2'
        checkLatest: true # Optional

    - task: Npm@1
      displayName: 'Install AutoRest'
      inputs:
        command: 'custom'
        customCommand: 'install -g autorest@latest'

    - task: Npm@1
      displayName: 'Install Rush'
      inputs:
        command: 'custom'
        customCommand: 'install -g @microsoft/rush'

