# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'PowerShellDocsUpdate Check'
schedules:
  - cron: "0 3 * * FRI"  # every Friday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
    displayName: 'PowerShellDocsUpdate Check'
    branches:
      include:
      - main
    always: true

parameters:
- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 1200
- name: CreatePullRequest
  type: boolean
  default: true

resources:
 repositories:     
   - repository: msgraph-sdk-powershell
     type: github
     endpoint: MicrosoftDocs
     name: microsoftgraph/msgraph-sdk-powershell
     ref: dev

   - repository: microsoft-graph-docs
     type: github
     endpoint: timayabi2020
     name: microsoftgraph/microsoft-graph-docs
     ref: main

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShellDocsUpdate
  pool: 
    name: 1es-windows-ps-compute
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  steps:
  - template: update-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'

  - task: PowerShell@2
    displayName: 'Generate markdown files from PowerShell help files'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: microsoftgraph-docs-powershell\scripts\GenerateMarkDown.ps1

  - task: PowerShell@2
    displayName: 'Escape disallowed html tags'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: microsoftgraph-docs-powershell\scripts\EscapeDisallowedHtmlTags.ps1

  # - task: PowerShell@2
  #   displayName: 'Update metadata header'
  #   continueOnError: false
  #   inputs:
  #     targetType: 'filePath'
  #     pwsh: true
  #     filePath: microsoftgraph-docs-powershell\scripts\MsProdUpdate.ps1

  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Examples to be reviewed as artifact'
  #   inputs:
  #     PathtoPublish: 'microsoftgraph-docs-powershell\missingexternaldocsurl'
  #     ArtifactName: 'MissingExternalDocs'
  #     publishLocation: 'Container'

  # - task: PowerShell@2
  #   displayName: 'Update Links'
  #   continueOnError: false
  #   inputs:
  #     targetType: 'filePath'
  #     pwsh: true
  #     filePath: microsoftgraph-docs-powershell\scripts\UpdateLinks.ps1
  
  - task: PowerShell@2
    displayName: 'Repair Examples and Descriptions and Title'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: microsoftgraph-docs-powershell\scripts\RepairExamplesDescriptionsAndTitle.ps1

  - task: PowerShell@2
    displayName: 'Remove boiler plate code'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: microsoftgraph-docs-powershell\scripts\RemoveBoilerPlateCode.ps1
      
  - task: PowerShell@2
    displayName: Pushing to github
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    inputs:
      targetType: inline
      pwsh: true
      script: |
        git config --global user.email "timwamalwa@gmail.com"
        git config --global user.name "Timothy Wamalwa"
        cd microsoftgraph-docs-powershell
        $date = Get-Date -Format "dd-MM-yyyy"
        $proposedBranch = "weekly_v2_docs_update_$date"
        git add .
        git commit -m "Updating help files $date"
        git push --set-upstream "https://$(GITHUB_TOKEN)@github.com/MicrosoftDocs/microsoftgraph-docs-powershell.git" $proposedBranch
        git status
      
  - template: common-templates/create-pr.yml
    parameters:
      BaseBranch: main
      Title: "Weekly PowerShell Microsoft Graph Reference Docs Refresh"
      Body: "This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR."