parameters:
  projectFileName: PowerShellDocsUpdate
  testType: 'Execution'
steps:
- task: PowerShell@2
  displayName: Install Required Modules
  inputs:
    targetType: 'inline'
    script: |
          $sdk = Get-InstalledModule Microsoft.Graph
          echo "Current version "+$sdk.Version
          echo "Updating to the latest sdk version"
          Update-Module Microsoft.Graph -Scope CurrentUser
          Import-Module Microsoft.Graph -Global -Force  

- template: checkout.yml
- template: install-tools-template.yml
  parameters:
    projectFileName: ${{ parameters.projectFileName }}
    runName: ${{ parameters.projectFileName }}
    testType: ${{ parameters.testType }}